---
title: "data analysis"
author: "Rana Gahwagy"
date: "5/7/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(ggplot2)
if (!require("ipumsr")) stop("Reading IPUMS data into R requires the ipumsr package. It can be installed using the following command: install.packages('ipumsr')")

ddi <- read_ipums_ddi("usa_00007.xml")
data <- read_ipums_micro(ddi)
```

```{r}
income_info <- data %>%
  filter(MARST == 1 | 6, 
         INCEARN > 0, 
         AGE >= 18) %>%
  #marries = 0 , single = 1
  mutate(MARST = ifelse(MARST == 1,0,1))
```

```{r}
set.seed(123)
index <- sample(1:nrow(income_info), replace = FALSE, size= 1000)
sample <- income_info[index, ]
```

```{r}
sample2 <- sample_n(income_info, 1000)
```

```{r}
m1 <- summary(lm(INCEARN ~ AGE+TRANTIME+UHRSWORK, data = sample))
m1
```

```{r}
m2 <- lm(INCEARN ~ AGE+TRANTIME+UHRSWORK+TRANTIME:UHRSWORK, data = sample)

```

```{r}
model_dataframe <- sample %>% 
  select(AGE,UHRSWORK, TRANTIME, INCEARN)

cor(model_dataframe)
```

```{r}
m3 <- lm(INCEARN ~ AGE+as.factor(SEX)+UHRSWORK, data = sample)
summary(m3)
```
```{r}
model_all <- lm(INCEARN ~ AGE+as.factor(RACE)+as.factor(MARST)+as.factor(SEX)+UHRSWORK+TRANTIME, data = sample)
summary(model_all)
```
```{r}
income_info_white <- data %>%
  filter(MARST == 1 | 6, 
         INCEARN > 0, 
         AGE >= 18) %>%
  #marries = 0 , single = 1
  mutate(MARST = ifelse(MARST == 1,0,1))

set.seed(123)
white_vs_other <- sample_n(income_info_white, 1000)

white_model <- lm(INCEARN ~ AGE+as.factor(RACE)+as.factor(MARST)+as.factor(SEX)+UHRSWORK+TRANTIME, data = white_vs_other)

summary(white_model)

```

```{r}
income_info_white <- data %>%
  filter(MARST == 1 | 6, 
         INCEARN > 0, 
         AGE >= 18) %>%
  #marries = 0 , single = 1
  mutate(MARST = ifelse(MARST == 1,0,1), 
         #0 = white , 1= non-white
         RACE = ifelse(RACE == 1,0,1))

set.seed(123)
white_vs_other <- sample_n(income_info_white, 1000)

white_model <- lm(log(INCEARN) ~ AGE+as.factor(RACE)+as.factor(MARST)+as.factor(SEX)+UHRSWORK, data = white_vs_other)

summary(white_model)

```
```{r}
# to determine race significance 
#all races
m5 <- lm(INCEARN ~ AGE+as.factor(RACE)+as.factor(MARST)+as.factor(SEX)+UHRSWORK+TRANTIME, data = sample_races)
#no race 
m6 <- lm(INCEARN ~ AGE+as.factor(MARST)+as.factor(SEX)+UHRSWORK+TRANTIME, data = sample_races)

anova(m6, m5) 
```

```{r}
# if transit is not significant and all races
m7 <- lm(INCEARN ~ AGE+as.factor(RACE)+as.factor(MARST)+as.factor(SEX)+UHRSWORK, data = sample_races)
#no race and no transit 
m8 <- lm(INCEARN ~ AGE+as.factor(MARST)+as.factor(SEX)+UHRSWORK, data = sample_races)

anova(m8, m7) # not sig => fail to reject 
summary(m7)

```

```{r}
#full
m9<- lm(INCEARN ~ AGE+as.factor(RACE)+as.factor(SEX)+UHRSWORK, data = sample_races)
#redu
m10<- lm(INCEARN ~ AGE+as.factor(SEX)+UHRSWORK, data = sample_races)

anova(m10, m9) # significan => reject null 
```


```{r}
summary(lm(INCEARN ~ AGE+as.factor(SEX)+UHRSWORK+as.factor(MARST), data = sample))
```
#final analysis 
#final datasample & models
```{r}
set.seed(123)
final_sample <-  sample_n(income_info, 1000)
final_model_full <- lm(INCEARN ~ AGE+as.factor(RACE)+as.factor(SEX)+UHRSWORK+TRANTIME, data = final_sample)
final_model <- lm(INCEARN ~ AGE+as.factor(RACE)+as.factor(SEX)+UHRSWORK, data = final_sample)
trans_final_model <- lm(log(INCEARN) ~ AGE+as.factor(RACE)+as.factor(SEX)+UHRSWORK, data = final_sample)

```
# data summary
```{r}
summary(trans_final_model)
```
```{r}
summary(final_model)
```
```{r}
summary(trans_final_model)
```
## visualzations 
###scatter plots 
```{r}
ggplot(data =final_sample, aes(x= AGE, y = INCEARN, color=as.factor(SEX),  shape= as.factor(MARST))) + 
         geom_point() 
       
ggplot(data =final_sample, aes(x=UHRSWORK , y = INCEARN, color=as.factor(SEX),  shape= as.factor(MARST ))) + 
         geom_point()

ggplot(data =final_sample, aes(x=UHRSWORK , y = INCEARN, color=as.factor(RACE),  shape= as.factor(SEX ))) + 
         geom_point()

ggplot(data =final_sample, aes(x=AGE , y = INCEARN, color=as.factor(RACE),  shape= as.factor(MARST))) + 
         geom_point()
```
###boxplots 
```{r}
ggplot(data =final_sample, aes(x= as.factor(SEX), y = INCEARN)) + 
         geom_boxplot()
ggplot(data =final_sample, aes(x= as.factor(MARST), y = INCEARN, color= as.factor(MARST))) + 
         geom_boxplot()
ggplot(data =final_sample, aes(x= as.factor(RACE), y = INCEARN)) + 
         geom_boxplot()
```

## liner regression conditions 
```{r}

ggplot(data = final_sample, aes(fitted.values(trans_final_model), resid(trans_final_model))) +
  geom_point() +
  geom_hline(yintercept = 0, col = "red", linetype = "dashed") +
  labs(x = "Fitted Values",
       y = "Residuals") +
  ggtitle("Residual vs Fitted Plot") +
  theme_bw()

ggplot(data = trans_final_model, aes(residuals(trans_final_model))) + 
  geom_histogram() +
  stat_bin(binwidth = 1) +
  ggtitle("Histogram of Residuals") + 
  xlab("Residuals")

ggplot(data = trans_final_model, aes(sample = residuals(trans_final_model))) +
  geom_qq() +
  geom_qq_line() +
  labs(x = "Theoretical Quantiles",
       y = "Sample Quantiles") +
  ggtitle("Normal Q-Q Plot")


```

